### ISSUE TITLE
suggestions: using stb style 

### ISSUE THREAD

**Issue by ayoubelmhamdi** [Warwolt/rktest#30]
When we have just two C files, a header, and source code file, it's much better for some people like me to use the STB-style, which is the single-header file library. It's very simple to integrate into the workflow, and in compilation, we don't need to specify any flags—just include it as a header file with the use
```c
#include <rktest.h>
#define RTEST_IMPLEMENTATION
```

**Comment by Warwolt** [comment]
Hm, that's an interesting idea. I do like the STB single-header libraries, but I'm not sure it's the best fit for all projects. I could easily see a project building the library once and just checking in the binary along with the header file into their source tree.

I'll consider having a "deploy" folder that builds a single-header version of the library, so that I can support consuming RK Test both as a CMake project and as a single-header library.

**Comment by ayoubelmhamdi** [comment]
Great idea.

**Comment by Warwolt** [comment]
Hi, I have now changed to a single-header style library with PR #31. It's still possible to build the project using CMake, but for people integrating other STB projects it should now be easier to include RK Test as well.
